services:
  db:
    container_name: 'user-todo-db2'
    image: 'mariadb:10.4.32'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_ROOT_PASSWORD=1234'
      - 'MYSQL_USER=myuser'
      - 'MYSQL_PASSWORD=secret'
    volumes:
      - user-todo-db2-data:/var/lib/mysql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    ports:
      - "3306:3306"

  phpmyadmin:
    container_name: "user-todo-phpmyadmin2"
    image: "phpmyadmin:5.2.1"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  user-todo-db2-data: